# Generated by Django 4.2.1 on 2023-05-21 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogo_sunat", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=50, verbose_name="Número Documento"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre Completo"),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo_sunat.tipodocumento",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.PositiveIntegerField(unique=True, verbose_name="Año")),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operacion",
                    models.CharField(
                        default="generar_guia", max_length=12, verbose_name="Operación"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "peso_bruto_total",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=22,
                        verbose_name="Peso Bruto Total",
                    ),
                ),
                (
                    "peso_bruto_unidad_medida",
                    models.CharField(
                        choices=[("KGM", "Kilogramos"), ("TNE", "Toneladas")],
                        max_length=3,
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "punto_partida_direccion",
                    models.CharField(
                        max_length=150, verbose_name="Punto de Partida (Dirección)"
                    ),
                ),
                (
                    "codigo_partida_establecimiento_sunat",
                    models.CharField(
                        max_length=4, verbose_name="Establecimiento Sunat"
                    ),
                ),
                (
                    "punto_llegada_direccion",
                    models.CharField(
                        max_length=150, verbose_name="Punto de Llegada (Dirección)"
                    ),
                ),
                (
                    "codigo_llegada_establecimiento_sunat",
                    models.CharField(
                        max_length=4, verbose_name="Establecimiento Sunat"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "enviar_cliente",
                    models.BooleanField(
                        max_length=5, verbose_name="Enviar automaticamente al cliente"
                    ),
                ),
                ("formato_pdf", models.CharField(max_length=5, verbose_name="Formato")),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.destinatario",
                        verbose_name="Destinatario / Cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaTransportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehiculo_principal",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TUC Vehículo principal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField(unique=True, verbose_name="Año")),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Tipo de Vehiculo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Yaer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2030),
                            django.core.validators.MinValueValidator(2000),
                        ],
                        verbose_name="Año",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=6, unique=True, verbose_name="Placa"),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                ("year", models.CharField(max_length=4, verbose_name="Año")),
                ("color", models.CharField(max_length=100, verbose_name="Color")),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.tipovehiculo",
                        verbose_name="Tipo de Vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=11, verbose_name="Numero del Documento"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo_sunat.tipodocumento",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaRemitente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_transporte",
                    models.CharField(
                        choices=[
                            ("01", "TRANSPORTE PÚBLICO"),
                            ("02", "TRANSPORTE PRIVADO"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "motivo_traslado_otro",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        verbose_name="Otro Motivo de Traslado",
                    ),
                ),
                (
                    "numero_de_bultos",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(999999),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Número de bultos",
                    ),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.guia",
                        verbose_name="Datos Generales de la Guia",
                    ),
                ),
                (
                    "motivo_traslado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo_sunat.motivotraslado",
                        verbose_name="Motivo de Traslado",
                    ),
                ),
                (
                    "transportista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.transportista",
                        verbose_name="Tansportista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_item", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="envios.guia"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.items",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guia",
            name="items",
            field=models.ManyToManyField(
                through="envios.GuiaItems", to="inventario.items"
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="placa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.vehiculos",
                verbose_name="Placa del vehiculo del transportista",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="punto_llegada",
            field=models.ForeignKey(
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llegada_remitente",
                to="catalogo_sunat.ubigeo",
                verbose_name="Punto de Llegada (Ubigeo)",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="punto_partida",
            field=models.ForeignKey(
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partida_remitente",
                to="catalogo_sunat.ubigeo",
                verbose_name="Punto de Partida (Ubigeo)",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="tipo_comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipocomprobante",
                verbose_name="Tipo de Comprobante",
            ),
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20, verbose_name="Numero del Documento"
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        max_length=250,
                        verbose_name="Razon o Nombre Completo (Conductor)",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                ("licencia", models.CharField(max_length=200, verbose_name="Licencia")),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.guia",
                        verbose_name="Guia",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo_sunat.tipodocumento",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
        ),
    ]
