# Generated by Django 4.2.1 on 2023-05-12 17:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Categoria Producto"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_de_documento",
                    models.CharField(max_length=15, verbose_name="Número de Documento"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=250, verbose_name="Email"),
                ),
                (
                    "email_1",
                    models.EmailField(
                        blank=True, max_length=250, verbose_name="Email 2"
                    ),
                ),
                (
                    "email_2",
                    models.EmailField(
                        blank=True, max_length=250, verbose_name="Email 3"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20, verbose_name="Numero del Documento"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "apellidos",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                ("licencia", models.CharField(max_length=200, verbose_name="Licencia")),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=2, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=70, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.PositiveIntegerField(unique=True, verbose_name="Año")),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operacion",
                    models.CharField(
                        default="generar_guia", max_length=12, verbose_name="Operación"
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="Número")),
                (
                    "fecha_emision",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "motivo_traslado_otro",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        verbose_name="Otro Motivo de Traslado",
                    ),
                ),
                (
                    "peso_bruto_total",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=22,
                        verbose_name="Peso Bruto Total",
                    ),
                ),
                (
                    "peso_bruto_unidad_medida",
                    models.CharField(
                        choices=[("KGM", "Kilogramos"), ("TNE", "Toneladas")],
                        max_length=3,
                        verbose_name="Unidad de medida",
                    ),
                ),
                (
                    "numero_de_bultos",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(999999),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Número de bultos",
                    ),
                ),
                (
                    "tipo_de_transporte",
                    models.CharField(
                        choices=[
                            ("01", "TRANSPORTE PÚBLICO"),
                            ("02", "TRANSPORTE PRIVADO"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "punto_partida_direccion",
                    models.TextField(max_length=150, verbose_name="Dirección"),
                ),
                (
                    "codigo_partida_establecimiento_sunat",
                    models.TextField(
                        max_length=4, verbose_name="Establecimiento Sunat"
                    ),
                ),
                (
                    "punto_llegada_direccion",
                    models.TextField(max_length=150, verbose_name="Dirección"),
                ),
                (
                    "codigo_llegada_establecimiento_sunat",
                    models.TextField(
                        max_length=4, verbose_name="Establecimiento Sunat"
                    ),
                ),
                ("observaciones", models.TextField(verbose_name="Observaciones")),
                (
                    "enviar_cliente",
                    models.BooleanField(
                        max_length=5, verbose_name="Enviar automaticamente al cliente"
                    ),
                ),
                ("formato_pdf", models.CharField(max_length=5, verbose_name="Formato")),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.conductor",
                        verbose_name="Conductor",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.cliente",
                        verbose_name="Destinatario / Cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField(unique=True, verbose_name="Año")),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotivoTraslado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Motivo de Traslado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=4, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="TipoComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                ("serie", models.CharField(max_length=4, verbose_name="Serie")),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="TipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Tipo de Vehiculo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Yaer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2030),
                            django.core.validators.MinValueValidator(2000),
                        ],
                        verbose_name="Año",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=6, unique=True, verbose_name="Placa"),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                ("year", models.CharField(max_length=4, verbose_name="Año")),
                ("color", models.CharField(max_length=100, verbose_name="Color")),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.tipovehiculo",
                        verbose_name="Tipo de Vehiculo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ubigeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6, verbose_name="Código")),
                ("nombre", models.CharField(max_length=50, verbose_name="Ubigeo")),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.provincia",
                        verbose_name="Provincia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=11, verbose_name="Numero del Documento"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "placa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.vehiculos",
                        verbose_name="Placa",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.tipodocumento",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                ("peso", models.PositiveIntegerField(verbose_name="Peso")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.categoriaproducto",
                        verbose_name="Categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaProductos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_guia_remitentes",
                    models.PositiveIntegerField(verbose_name="Cantidad"),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="envios.guia"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guia",
            name="motivo_traslado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.motivotraslado",
                verbose_name="Motivo de Traslado",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="punto_llegada",
            field=models.ForeignKey(
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llegada_remitente",
                to="envios.ubigeo",
                verbose_name="Ubigeo",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="punto_partida",
            field=models.ForeignKey(
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partida_remitente",
                to="envios.ubigeo",
                verbose_name="Ubigeo",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="remitentes_productos",
            field=models.ManyToManyField(
                through="envios.GuiaProductos", to="envios.producto"
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="tipo_comprobante",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.tipocomprobante",
                verbose_name="Tipo de Comprobante",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="transportista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.transportista",
                verbose_name="Tansportista",
            ),
        ),
        migrations.AddField(
            model_name="conductor",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_documento_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
