# Generated by Django 4.2.1 on 2023-05-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("envios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guiaremitente",
            name="numero",
            field=models.CharField(max_length=10, null=True, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_comprobante",
            field=models.CharField(
                choices=[
                    ("7", "GUÍA REMISIÓN REMITENTE"),
                    ("8", "GUÍA REMISIÓN TRANSPORTISTA"),
                ],
                max_length=2,
                verbose_name="Tipo de Comprobante",
            ),
        ),
    ]
