# Generated by Django 4.2.1 on 2023-05-13 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("envios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Categoria Item"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_item", models.PositiveIntegerField(verbose_name="Cantidad")),
            ],
        ),
        migrations.CreateModel(
            name="GuiaRemitente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_transporte",
                    models.CharField(
                        choices=[
                            ("01", "TRANSPORTE PÚBLICO"),
                            ("02", "TRANSPORTE PRIVADO"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "motivo_traslado_otro",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        verbose_name="Otro Motivo de Traslado",
                    ),
                ),
                (
                    "numero_de_bultos",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(999999),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Número de bultos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuiaTransportista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehiculo_principal",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TUC Vehículo principal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                ("peso", models.PositiveIntegerField(verbose_name="Peso")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="envios.categoriaitem",
                        verbose_name="Categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Tipo Item")),
            ],
        ),
        migrations.RemoveField(
            model_name="guiaproductos",
            name="guia",
        ),
        migrations.RemoveField(
            model_name="guiaproductos",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="conductor",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="motivo_traslado",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="motivo_traslado_otro",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="numero_de_bultos",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="remitentes_productos",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="tipo_de_transporte",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="transportista",
        ),
        migrations.RemoveField(
            model_name="transportista",
            name="placa",
        ),
        migrations.AddField(
            model_name="conductor",
            name="denominacion",
            field=models.CharField(
                max_length=250,
                null=True,
                verbose_name="Razon o Nombre Completo (Conductor)",
            ),
        ),
        migrations.AddField(
            model_name="conductor",
            name="guia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.guia",
                verbose_name="Guia",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="placa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.vehiculos",
                verbose_name="Placa del vehiculo del transportista",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.tipocomprobante",
                verbose_name="Tipo de Comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculos",
            name="placa",
            field=models.CharField(
                max_length=6, null=True, unique=True, verbose_name="Placa"
            ),
        ),
        migrations.DeleteModel(
            name="CategoriaProducto",
        ),
        migrations.DeleteModel(
            name="GuiaProductos",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
        migrations.AddField(
            model_name="items",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.tipoitem",
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AddField(
            model_name="guiaremitente",
            name="guia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.guia",
                verbose_name="Datos Generales de la Guia",
            ),
        ),
        migrations.AddField(
            model_name="guiaremitente",
            name="motivo_traslado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.motivotraslado",
                verbose_name="Motivo de Traslado",
            ),
        ),
        migrations.AddField(
            model_name="guiaremitente",
            name="transportista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.transportista",
                verbose_name="Tansportista",
            ),
        ),
        migrations.AddField(
            model_name="guiaitems",
            name="guia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="envios.guia"
            ),
        ),
        migrations.AddField(
            model_name="guiaitems",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.items",
            ),
        ),
        migrations.AddField(
            model_name="guia",
            name="items",
            field=models.ManyToManyField(through="envios.GuiaItems", to="envios.items"),
        ),
    ]
