# Generated by Django 4.2.1 on 2023-05-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("inventario", "0001_initial"),
        ("catalogo_sunat", "0001_initial"),
        ("envios", "0002_categoriaitem_destinatario_guiaitems_guiaremitente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="tipo_documento_cliente",
        ),
        migrations.RemoveField(
            model_name="items",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="items",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="ubigeo",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="ubigeo",
            name="provincia",
        ),
        migrations.RemoveField(
            model_name="guia",
            name="numero",
        ),
        migrations.AddField(
            model_name="destinatario",
            name="nombre",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Nombre Completo"
            ),
        ),
        migrations.AddField(
            model_name="destinatario",
            name="numero_documento",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Número Documento"
            ),
        ),
        migrations.AddField(
            model_name="destinatario",
            name="tipo_documento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="codigo_llegada_establecimiento_sunat",
            field=models.CharField(max_length=4, verbose_name="Establecimiento Sunat"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="codigo_partida_establecimiento_sunat",
            field=models.CharField(max_length=4, verbose_name="Establecimiento Sunat"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="destinatario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.cliente",
                verbose_name="Destinatario / Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="items",
            field=models.ManyToManyField(
                through="envios.GuiaItems", to="inventario.items"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="punto_llegada",
            field=models.ForeignKey(
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llegada_remitente",
                to="catalogo_sunat.ubigeo",
                verbose_name="Punto de Llegada (Ubigeo)",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="punto_llegada_direccion",
            field=models.CharField(
                max_length=150, verbose_name="Punto de Llegada (Dirección)"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="punto_partida",
            field=models.ForeignKey(
                max_length=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partida_remitente",
                to="catalogo_sunat.ubigeo",
                verbose_name="Punto de Partida (Ubigeo)",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="punto_partida_direccion",
            field=models.CharField(
                max_length=150, verbose_name="Punto de Partida (Dirección)"
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipocomprobante",
                verbose_name="Tipo de Comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="guiaitems",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.items",
            ),
        ),
        migrations.AlterField(
            model_name="guiaremitente",
            name="motivo_traslado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.motivotraslado",
                verbose_name="Motivo de Traslado",
            ),
        ),
        migrations.AlterField(
            model_name="transportista",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.DeleteModel(
            name="CategoriaItem",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Departamento",
        ),
        migrations.DeleteModel(
            name="Items",
        ),
        migrations.DeleteModel(
            name="MotivoTraslado",
        ),
        migrations.DeleteModel(
            name="Provincia",
        ),
        migrations.DeleteModel(
            name="TipoComprobante",
        ),
        migrations.DeleteModel(
            name="TipoDocumento",
        ),
        migrations.DeleteModel(
            name="TipoItem",
        ),
        migrations.DeleteModel(
            name="Ubigeo",
        ),
    ]
