# Generated by Django 4.2.1 on 2023-05-22 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_alter_cliente_nombre"),
        ("catalogo_sunat", "0003_alter_ubigeo_nombre"),
        ("envios", "0003_remove_conductor_guia_conductor_guia_remitente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conductor",
            name="guia_remitente",
        ),
        migrations.AddField(
            model_name="guia",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="guiaremitente",
            name="conductor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.conductor",
                verbose_name="Conductor",
            ),
        ),
        migrations.AddField(
            model_name="guiatransportista",
            name="conductor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="envios.conductor",
                verbose_name="Conductor",
            ),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="apellidos",
            field=models.CharField(max_length=250, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="denominacion",
            field=models.CharField(
                max_length=100, verbose_name="Razon o Nombre Completo (Conductor)"
            ),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="licencia",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(9),
                    django.core.validators.MaxLengthValidator(10),
                ],
                verbose_name="Licencia",
            ),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="nombre",
            field=models.CharField(max_length=250, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="conductor",
            name="numero_documento",
            field=models.CharField(max_length=15, verbose_name="Numero del Documento"),
        ),
        migrations.AlterField(
            model_name="destinatario",
            name="numero_documento",
            field=models.CharField(max_length=15, verbose_name="Número Documento"),
        ),
        migrations.AlterField(
            model_name="guia",
            name="punto_llegada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llegada_remitente",
                to="catalogo_sunat.ubigeo",
                verbose_name="Punto de Llegada (Ubigeo)",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="punto_partida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partida_remitente",
                to="catalogo_sunat.ubigeo",
                verbose_name="Punto de Partida (Ubigeo)",
            ),
        ),
        migrations.AlterField(
            model_name="guia",
            name="tipo_comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipocomprobante",
                verbose_name="Tipo de Comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="guiaremitente",
            name="numero_de_bultos",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxLengthValidator(999999),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Número de bultos",
            ),
        ),
        migrations.AlterField(
            model_name="guiatransportista",
            name="vehiculo_principal",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxLengthValidator(15),
                ],
                verbose_name="TUC Vehículo principal",
            ),
        ),
        migrations.AlterField(
            model_name="transportista",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="yaer",
            name="year",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(2030),
                    django.core.validators.MinValueValidator(2000),
                ],
                verbose_name="Año",
            ),
        ),
    ]
