# Generated by Django 4.2.1 on 2023-05-25 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("envios", "0005_guiatransportista_numero_alter_guiaremitente_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guia",
            name="fecha_emision",
        ),
    ]
