# Generated by Django 4.2.1 on 2023-05-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("envios", "0006_remove_guia_fecha_emision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conductor",
            name="licencia",
            field=models.CharField(max_length=10, verbose_name="Licencia"),
        ),
    ]
