# Generated by Django 4.2.1 on 2023-05-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("envios", "0007_alter_conductor_licencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conductor",
            name="numero_documento",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Numero del Documento"
            ),
        ),
        migrations.AlterField(
            model_name="transportista",
            name="numero_documento",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="Numero del Documento"
            ),
        ),
    ]
