# Generated by Django 4.2.1 on 2023-05-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("envios", "0008_alter_conductor_numero_documento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guiatransportista",
            name="vehiculo_principal",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="TUC Vehículo principal",
            ),
        ),
    ]
