# Generated by Django 4.2.1 on 2023-05-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("catalogo_sunat", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operacion",
                    models.CharField(
                        default="generar_comprobante",
                        max_length=50,
                        verbose_name="Operación",
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        choices=[(18, "ESTANDAR"), (10, "LEY 31556"), (4, "IVAP")],
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="IGV",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tipo de cambio"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de emisión"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Porcentaje de descuento",
                    ),
                ),
                (
                    "total_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Descuento Total (-)",
                    ),
                ),
                (
                    "total_anticipo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Anticipo (-)",
                    ),
                ),
                (
                    "total_inafecta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Inafecta",
                    ),
                ),
                (
                    "total_gravado",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Gravada"
                    ),
                ),
                (
                    "total_exonerada",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Exonerada"
                    ),
                ),
                (
                    "total_igv",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="IGV"
                    ),
                ),
                (
                    "total_gratuita",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Gratuita"
                    ),
                ),
                (
                    "total_otros_cargos",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Otros Cargos"
                    ),
                ),
                (
                    "total_isc",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="ICBPERS"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total"
                    ),
                ),
                ("estado_pago", models.BooleanField(verbose_name="¿Pagado?")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6, verbose_name="Código")),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
        ),
        migrations.CreateModel(
            name="TipoPercepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, verbose_name="Tipo de percepcion"),
                ),
                (
                    "tasa",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Tipo de Documento"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturaItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_item", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ventas.factura"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.items",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="factura",
            name="items",
            field=models.ManyToManyField(
                through="ventas.FacturaItems",
                to="inventario.items",
                verbose_name="Items",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="moneda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.moneda",
                verbose_name="Moneda",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="sunat_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.tipooperacion",
                verbose_name="Tipo Operación",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tipo_comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogo_sunat.tipocomprobante",
                verbose_name="Tipo de Comprobante",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="tipo_percepcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.tipopercepcion",
                verbose_name="",
            ),
        ),
    ]
