# Generated by Django 4.2.1 on 2023-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo_sunat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serie",
            name="numero",
        ),
        migrations.AlterField(
            model_name="serie",
            name="nombre",
            field=models.CharField(max_length=4, unique=True, verbose_name="Nombre"),
        ),
    ]
