# Generated by Django 4.2.1 on 2023-05-19 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo_sunat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provincia",
            options={"verbose_name": "Provincia", "verbose_name_plural": "Provincias"},
        ),
    ]
