# Generated by Django 4.2.1 on 2023-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo_sunat", "0002_remove_serie_numero_alter_serie_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubigeo",
            name="nombre",
            field=models.CharField(max_length=150, verbose_name="Ubigeo"),
        ),
    ]
